// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmstewknmipfvuqojfxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtc3Rld2tubWlwZnZ1cW9qZnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTQ3NjUsImV4cCI6MjA1OTgzMDc2NX0.aN3eGIxbiV-9ug1G3RiekxtLxkIWbOiJJsTYdAfmD6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);